page_url = 'cards_builder'

input_cart_name = '[id="validationCardName"]'
select_source = '[formcontrolname="provider"]'
input_provider = '[formcontrolname="provider"] [aria-autocomplete="list"]'
source_first = '/html/body/app-dashboard/div/main/div/cards-builder/div[2]/div[1]/div/div[1]/div[1]/div[2]/div/button'
select_type = '[formcontrolname="type"]'
limit_type = '/html/body/app-dashboard/div/main/div/cards-builder/div[2]/div[1]/form/div[1]/div[2]/div/div[2]/ng-select/ng-dropdown-panel/div/div[2]/div/span'
imput_number = '[class="p-inputnumber p-component"] [class="p-inputtext p-component p-element p-inputnumber-input p-filled"]'
select_limit_rule = '[formcontrolname="limit_rule"]'
rule_monthly = '//div[contains(text(), \'monthly\')]'
input_3d_secure_password = '[formcontrolname="secure_3d_password"]'
button_submit = '[type="submit"]'
block_verify_acc = '/html/body/app-dashboard/div/main/div/cards-builder/div[2]/div[1]/form/div[4]/div[2]'