page_url = 'blockchain_wallets'

button_add = '[class="btn d-inline-block btn-base mobileGrow mobileWidthAuto"]'
select_blockchain = '[formcontrolname="blockchain"]'
blockchain_option = '//span[contains(text(), \'tron\')]'
input_address = '[formcontrolname="address"]'
button_submit = '[class="btn btn-base"]'
toast_success = '[class*="adc-toast-error"]'
button_delete_wallet = '[class="btn btn-sm btn-default"]'
button_confirm_delete_wallet = '[class="modal-footer btnMw150"] [class="btn btn-base"]'
toast_success2 = '[class*="adc-toast-title"]'
